FROM maven:3.5.4-jdk-8-alpine as maven

COPY ./pom.xml ./pom.xml
COPY ./src ./src

RUN mvn --version
RUN mvn dependency:go-offline -B
RUN mvn package


FROM openjdk:8u171-jre-alpine

WORKDIR /petclinic-rest
COPY --from=maven target/spring-petclinic-rest-*.jar ./spring-petclinic-rest.jar

RUN java -version
RUN java -jar ./spring-petclinic-rest.jar &

EXPOSE 9966


FROM postman/newman:5

RUN newman --version
RUN newman run https://api.getpostman.com/collections/14312820-c39aca89-b267-4d97-a2ca-b65df579f9fa?apikey=PMAK-60101515c9205f003495db6d-37971a23f29ae9913c6657a8fe028239f5 \
  --environment https://api.getpostman.com/environments/14312820-58506620-e644-46ff-a263-1884e7935177?apikey=PMAK-60101515c9205f003495db6d-37971a23f29ae9913c6657a8fe028239f5