# active profile config
#
# the active profile selects the database
# (the repository layer is always Spring JDBC)
# ------------------------------------------------
# When using MySQL, use: mysql
# When using H2, use: h2
# ------------------------------------------------

spring.profiles.active=h2

# ------------------------------------------------

server.port=9966
server.servlet.context-path=/petclinic/

# Default database platform; can be overridden by other profile-specific property sources 
spring.sql.init.platform=h2
# Ensures schema & data reload on every restart (good for local dev)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:db/${spring.sql.init.platform}/schema.sql
spring.sql.init.data-locations=classpath*:db/${spring.sql.init.platform}/data.sql

spring.messages.basename=messages/messages

# OpenAPI/Swagger UI (Defaults to true)
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true

logging.level.org.springframework=INFO
logging.level.org.springframework.samples.petclinic=DEBUG
#logging.level.org.springframework=DEBUG

# enable the desired authentication type
# by default, the authentication is disabled
petclinic.security.enable=false

