# database init, supports mysql too
spring.sql.init.platform=mysql
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost/petclinic}
spring.datasource.username=root
spring.datasource.password=gitesh
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
