INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('read-client', 'rest-server',
	/*read-client-password123*/'$2a$04$9FpRAy2E1NqHK35GwZvHee2RJlyshqyEnHq0e5r0mzB7GLjQQ0NKG',
	'read', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);

INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('write-client', 'rest-server',
	/*write-client-password123*/'$2a$04$aWnuFg.7NMS5mOgYAVZ41.08HWK41mxDMx6fHgOtXU/Ixtl9LOTei',
	'read,write', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);	