INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'OWNER_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'OWNER_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'OWNER_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'OWNER_DELETE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (5, 'PET_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (6, 'PET_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (7, 'PET_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (8, 'PET_DELETE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (9, 'ROLE_PETCLINIC_READER');
INSERT INTO AUTHORITY(ID, NAME) VALUES (10, 'ROLE_PETCLINIC_WRITER');

INSERT INTO AUTHORITY(ID, NAME) VALUES (11, 'VET_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (12, 'VET_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (13, 'VET_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (14, 'VET_DELETE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (15, 'SPEC_CREATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (16, 'SPEC_READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (17, 'SPEC_UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (18, 'SPEC_DELETE');